// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAlertConfig = `-- name: CreateAlertConfig :one
INSERT INTO alert_configs (project_id, alert_type, config, enabled, level_filter, title_pattern)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern
`

type CreateAlertConfigParams struct {
	ProjectID    uuid.UUID       `json:"project_id"`
	AlertType    string          `json:"alert_type"`
	Config       json.RawMessage `json:"config"`
	Enabled      bool            `json:"enabled"`
	LevelFilter  string          `json:"level_filter"`
	TitlePattern string          `json:"title_pattern"`
}

func (q *Queries) CreateAlertConfig(ctx context.Context, arg CreateAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, createAlertConfig,
		arg.ProjectID,
		arg.AlertType,
		arg.Config,
		arg.Enabled,
		arg.LevelFilter,
		arg.TitlePattern,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AlertType,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LevelFilter,
		&i.TitlePattern,
	)
	return i, err
}

const deleteAlertConfig = `-- name: DeleteAlertConfig :exec
DELETE FROM alert_configs WHERE id = $1
`

func (q *Queries) DeleteAlertConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAlertConfig, id)
	return err
}

const getEnabledAlerts = `-- name: GetEnabledAlerts :many
SELECT id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern FROM alert_configs WHERE project_id = $1 AND enabled = true
`

func (q *Queries) GetEnabledAlerts(ctx context.Context, projectID uuid.UUID) ([]AlertConfig, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledAlerts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertConfig{}
	for rows.Next() {
		var i AlertConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AlertType,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LevelFilter,
			&i.TitlePattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertConfigs = `-- name: ListAlertConfigs :many
SELECT id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern FROM alert_configs WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListAlertConfigs(ctx context.Context, projectID uuid.UUID) ([]AlertConfig, error) {
	rows, err := q.db.QueryContext(ctx, listAlertConfigs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertConfig{}
	for rows.Next() {
		var i AlertConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AlertType,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LevelFilter,
			&i.TitlePattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertConfig = `-- name: UpdateAlertConfig :one
UPDATE alert_configs
SET config = $2, enabled = $3, level_filter = $4, title_pattern = $5, updated_at = now()
WHERE id = $1
RETURNING id, project_id, alert_type, config, enabled, created_at, updated_at, level_filter, title_pattern
`

type UpdateAlertConfigParams struct {
	ID           uuid.UUID       `json:"id"`
	Config       json.RawMessage `json:"config"`
	Enabled      bool            `json:"enabled"`
	LevelFilter  string          `json:"level_filter"`
	TitlePattern string          `json:"title_pattern"`
}

func (q *Queries) UpdateAlertConfig(ctx context.Context, arg UpdateAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRowContext(ctx, updateAlertConfig,
		arg.ID,
		arg.Config,
		arg.Enabled,
		arg.LevelFilter,
		arg.TitlePattern,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AlertType,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LevelFilter,
		&i.TitlePattern,
	)
	return i, err
}
