// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AlertConfig struct {
	ID           uuid.UUID       `json:"id"`
	ProjectID    uuid.UUID       `json:"project_id"`
	AlertType    string          `json:"alert_type"`
	Config       json.RawMessage `json:"config"`
	Enabled      bool            `json:"enabled"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	LevelFilter  string          `json:"level_filter"`
	TitlePattern string          `json:"title_pattern"`
}

type Event struct {
	ID             uuid.UUID       `json:"id"`
	IssueID        uuid.UUID       `json:"issue_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	EventID        string          `json:"event_id"`
	Timestamp      time.Time       `json:"timestamp"`
	Platform       string          `json:"platform"`
	Level          string          `json:"level"`
	Message        string          `json:"message"`
	Release        string          `json:"release"`
	Environment    string          `json:"environment"`
	ServerName     string          `json:"server_name"`
	Data           json.RawMessage `json:"data"`
	CreatedAt      time.Time       `json:"created_at"`
	UserIdentifier string          `json:"user_identifier"`
}

type Issue struct {
	ID                   uuid.UUID      `json:"id"`
	ProjectID            uuid.UUID      `json:"project_id"`
	Title                string         `json:"title"`
	Fingerprint          string         `json:"fingerprint"`
	Status               string         `json:"status"`
	Level                string         `json:"level"`
	Platform             string         `json:"platform"`
	FirstSeen            time.Time      `json:"first_seen"`
	LastSeen             time.Time      `json:"last_seen"`
	EventCount           int32          `json:"event_count"`
	AssignedTo           uuid.NullUUID  `json:"assigned_to"`
	ResolvedAt           sql.NullTime   `json:"resolved_at"`
	CooldownUntil        sql.NullTime   `json:"cooldown_until"`
	ResolvedInRelease    sql.NullString `json:"resolved_in_release"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	SnoozeUntil          sql.NullTime   `json:"snooze_until"`
	SnoozeEventThreshold sql.NullInt32  `json:"snooze_event_threshold"`
	SnoozeEventsAtStart  int32          `json:"snooze_events_at_start"`
}

type Project struct {
	ID                     uuid.UUID `json:"id"`
	Name                   string    `json:"name"`
	Slug                   string    `json:"slug"`
	DefaultCooldownMinutes int32     `json:"default_cooldown_minutes"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	WarningAsError         bool      `json:"warning_as_error"`
}

type ProjectKey struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	PublicKey string    `json:"public_key"`
	SecretKey string    `json:"secret_key"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Role      string         `json:"role"`
	GoogleID  sql.NullString `json:"google_id"`
	AvatarUrl string         `json:"avatar_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Status    string         `json:"status"`
}
