ALTER TABLE alert_configs ADD COLUMN IF NOT EXISTS min_events INT NOT NULL DEFAULT 0;
ALTER TABLE alert_configs ADD COLUMN IF NOT EXISTS min_velocity_1h INT NOT NULL DEFAULT 0;
ALTER TABLE alert_configs ADD COLUMN IF NOT EXISTS exclude_pattern TEXT NOT NULL DEFAULT '';
