DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS alert_configs;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS project_keys;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
